name: Run Tests on Pull Request

on:
  workflow_call:
    inputs:
      error_log_test:
        description: "El log de error que viene del paso de tests"
        type: string
        required: false
      error_log_lint:
        description: "El log de error que viene del paso de lint"
        type: string
        required: false

jobs:

  jules-connect:
    name: Get issues in lint/test and call jules
    runs-on: ubuntu-latest
    environment: PROD
    
    steps:
    
      - name: get lint
        run: |
          echo ${{ inputs.error_log_lint }}
          
      - name: get test
        run: |
          echo ${{ inputs.error_log_test }}

      - name: join issues

      - name: request
        if: failure()
        uses: google-labs-code/jules-invoke@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          prompt: |
            The CI pipeline failed during the lint/test phase.
            Please analyze the following error logs and apply a fix to the repository:
            ${{ env.log_content }}
          jules_api_key: ${{ secrets.API_KEY_JULES }}
          starting_branch: ${{ github.head_ref || github.ref_name }}
